version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: if [[ -z "${DOCKER_USERNAME}" ]]; then echo "$DOCKER_USERNAME not set. Exiting."; exit -1; else echo "Env check OK."; fi

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: docker_global