version: 2.1
parameters:
  SMOKE_TEST:
    type: boolean
    default: false
  DEPLOYMENT:
    type: boolean
    default: false
jobs:
  myjob:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - run: echo "<< pipeline.id >>"
      - run:
        name: Check pipeline with API
        command: |
          build_status=$(curl POST --header "Content-Type: application/json" -u '0232224beae7b08beb3b0913907ac58efc79328a': https://circleci.com/api/v2/pipeline/5046386c-f12d-469a-a1e2-5ec6f41f7a4b/workflow | jq '.items[0].status')
          if [ "${build_status}" = "success" ] then
            echo "build trigger!"
          else
            echo "don't trigger the build"
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob