version: 2
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:201908-06
    steps:
    - run: choco install -y dotnet3.5 --version=3.5.20160716
workflows:
  version: 2
  workflow:
    jobs:
    - build