version: 2.1

jobs:
  restore_cache_build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: source-v1--
      # if cache successfully restored, then there would be path
      - run:
          name: check cache path
          command: |
            CACHE_DIR="~/projectPath"
            echo ([ -d "$CACHE_DIR" ])
      - run:
          name: check when
          command: |
            if [ $? == 1 ]; then
              echo "hello world"
            fi
workflows:
  start_build:
    jobs:
      - restore_cache_build
