version: 2.1
jobs:
  myjob:
    docker:
    - image: circleci/node:10.17.0
    parameters:
      sophie:
        type: string
        default: ""
      dophie:
        type: boolean
        default: false
    steps:
    - checkout
    - when:
        condition: <<parameters.sophie>> or <<parameters.dophie>>
        steps:
          - run: echo "my custom checkout"
    # - unless:
    #     condition: <<parameters.custom_checkout>>
    #     steps:
    #       - checkout
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: aws