version: 2.1
jobs:
  build:
    docker:
    - image: google/cloud-sdk:alpine
    steps:
    - checkout
    - run: apk add libc6-compat libstdc++ libgcc
    - run:
        name: install node version 10
        command: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
          echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'  >> $BASH_ENV
          echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> $BASH_ENV  # This loads nvm bash_completion
          source $BASH_ENV
    - run:
        name: Check node
        command: |
          nvm install 10.19.0
          nvm alias default 10.19.0
          node -v
          which node
workflows:
  version: 2
  workflow:
    jobs:
    - build