version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: if [[ -z "${password}" ]]; then echo "$password not set. Exiting."; exit -1; else echo "$password Env check OK."; fi

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: test-context