version: 2.0
jobs:
  build:
    machine:
      docker_layer_caching: true
    # docker:
    #   - image: circleci/node:8.15.1
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: install nodejs
          command: |
            if [[ $(node -v) == "" ]]; then
              sudo apt install nodejs
            else
              echo "NodeJS is already installed"
            fi
      - run:
          name: install java
          command: |
            java -version
            if java -version 2>&1 >/dev/null | grep "java version\|openjdk version" ; then
              echo "Java JDK is already installed"
            else
              sudo apt-get update && sudo apt install openjdk-8-jdk
            fi