version: 2.1
jobs:
  build:
    docker:
    - image: google/cloud-sdk:alpine
    steps:
    - checkout
    - run:
        name: install node version 10
        command: |
          apk add nodejs --update-cache --repository https://deb.nodesource.com/setup_10.x --allow-untrusted
    - run:
        name: Check node version
        command: node -v
workflows:
  version: 2
  workflow:
    jobs:
    - build