version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            uname
            sudo apt-get update && sudo apt-get install default-jdk
