version: 2.1

jobs:
  myjob:
    docker:
      - image: circleci/node:8.11-browsers
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout

workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: test-context