version: 2.1
parameters:
  SMOKE_TEST:
    type: boolean
    default: false
  DEPLOYMENT:
    type: boolean
    default: false
jobs:
  myjob:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - run: echo "<< pipeline.id >>"
      - run:
        name: Check pipeline with API
        command: |
          curl -X GET https://circleci.com/api/v2/pipeline/5046386c-f12d-469a-a1e2-5ec6f41f7a4b/workflow \
    -H 'Accept: application/json' | jq '.items[0].status'
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob