version: 2.1
jobs:
  myjob:
    docker:
      - image: circleci/python:3.6.6-node-browsers
    steps:
      - run:
          name: Check node version
          command: node -v
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob