version: 2.0
jobs:
  build:
    machine:
      docker_layer_caching: true
    # docker:
    #   - image: circleci/node:8.15.1
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          command: |
            uname
            sudo apt-get update
            sudo apt install nodejs
            sudo apt install openjdk-8-jdk
      
      - run:
          command: |
            java -v
            node -v
