version: 2.1
jobs:
  cmake:
    docker:
    - image: circleci/ruby:2.6.4-node-browsers
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - cmake
