version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8.11
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          command: |
            java --version
            npm -v
