version: 2.1
parameters:
  SMOKE_TEST:
    type: boolean
    default: false
  DEPLOYMENT:
    type: boolean
    default: false
jobs:
  myjob:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - run: echo "<< pipeline.id >>"
  #   - run:
  #     name: Check pipeline with API
  #     command: curl -X GET https://circleci.com/api/v2/pipeline/{pipeline-id}/workflow \
  # -H 'Accept: application/json' | jq 
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob