version: 2.1
jobs:
  build:
    docker:
    - image: google/cloud-sdk:alpine
    steps:
    - checkout
    # - run: apk add --no-cache libstdc++ libc6-compat gcompat
    # - run: apk add libgcc
    # - run: apk info -vv | sort
    - run:
        name: install node version 10
        command: |
          curl "http://nodejs.org/dist/v10.19.0/node-v10.19.0.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"

    - run:
        name: Check node
        command: |
          node -v
workflows:
  version: 2
  workflow:
    jobs:
    - build

