version: 2.1

jobs:
  myjob:
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout
      - run: echo "$CART_EXPIRY $CART_STRING"
    environment:
      CART_EXPIRY: 2629746
      CART_STRING: "2629746"

workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: test-context