version: 2.1
jobs:
  codecheck:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "test code"

  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "test build"

workflows:
  version: 2
  build:
    jobs:
      - codecheck:
          filters:
            branches:
              ignore:
                - /(master|alpha|beta|production)/
      - test:
          filters:
            branches:
              ignore:
                - /alpha/