version: 2.1
jobs:
  persistWorkspace:
    docker:
      - image: circleci/node:10
    working_directory: ~/config
    steps:
      - checkout 
      - persist_to_workspace:
          root: .
          path: test
  attachWorkspace:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ~/config

workflows:
  version: 2
  build-deploy:
    jobs:
      - persistWorkspace
      - attachWorkspace:
          requires:
            - persistWorkspace
          