version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa   
            sudo apt-get update   
            sudo apt install python3.8 

      - run:
          command: |
            python3.8 -V