version: 2.1

jobs:
  myjob:
    docker:
    - image: circleci/node:10.17.0
    steps:
    - checkout
    - run:
        command:
          pwd

workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: test-context