version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: pyenv version
          command: |
            pyenv version
            pyenv install --list
workflows:
  version: 2
  workflow:
    jobs:
    - build
