version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01)
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install python 3.8
            python -V
