version: 2.0
jobs:
  build:
    machine:
      docker_layer_caching: true
    # docker:
    #   - image: circleci/node:8.15.1
    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          command: |
            if [[ $(java -version) == "" ]]; then
              sudo apt-get update && sudo apt install openjdk-8-jdk
            else
              echo "Java JDK is already installed"
            if [[ $(node -v) == "" ]]; then
              sudo apt install nodejs
            else
              echo "NodeJS is already installed"
            fi
