version: 2.1

jobs:
  myjob:
    docker:
      - image: circleci/php:7.3-stretch
    steps:
      - checkout

workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: test-context