version: 2.1
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps:
    - checkout
    - run:
        name: Download latest Media framework
        command: |
          mkdir -p media
          curl https://amazon-chime-sdk.s3.amazonaws.com/ios/amazon-chime-sdk-media/latest/AmazonChimeSDKMedia.tar.gz -o media/AmazonChimeSDKMedia.tar.gz
          tar -xvzf media/AmazonChimeSDKMedia.tar.gz -C media
          cp -R media/AmazonChimeSDKMedia.framework AmazonChimeSDK/
    - run:
        name: Run unit test
        command: xcodebuild -project AmazonChimeSDK/AmazonChimeSDK.xcodeproj -scheme AmazonChimeSDKTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' test
    - run:
        name: Build SDK
        command: xcodebuild -project AmazonChimeSDK/AmazonChimeSDK.xcodeproj build
    - store_artifacts:
        path: build
workflows:
  version: 2
  workflow:
    jobs:
    - build