version: 2.1
jobs:
  build:
    docker:
    - image: google/cloud-sdk:alpine
    steps:
    - checkout
    - run:
        name: install node version 10
        command: |
          curl -sL https://deb.nodesource.com/setup_10.19.0 -o nodesource_setup.sh

    - run:
        name: Check node
        command: |
          sudo bash nodesource_setup.sh
workflows:
  version: 2
  workflow:
    jobs:
    - build

