version: 2.1
jobs:
  myjob:
    docker:
    - image: circleci/node:10.17.0
    parameters:
      sophie:
        type: string
        default: ""
    steps:
    - checkout
    - run:
        name: Create build folder
        command: |
          npm i
          ls
          echo << parameters.sophie >>
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: aws