version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
      - image: microsoft/dotnet:2-sdk
    steps:
      - run: echo "hello world"
workflows:
  build_and_push_image:
    jobs:
      - build
