version: 2.0
parameters:
  macos:
    type: boolean
    default: false
  ubuntu_machine:
    type: boolean
    default: false
  build_and_deploy:
    type: boolean
    default: true
workflows:
  version: 2
  macos:
    jobs:
      - show_xcode_version:
          context: test-context
  ubuntu_machine:
    jobs:
      - show_ubuntu_whois
  test:
    jobs:
      - splitting-test
      - test:
          requires:
            - splitting-test
jobs:
  show_xcode_version:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - restore_cache:
          key: homebrew
      - attach_workspace:
          at: ./
      - run:
          command: |
            xcodebuild -version
            echo ${password}
      - run:
          command: brew update
      - run:
          command: brew install Gradle
  show_ubuntu_whois:
    branches:
      only:
        - /develop-/i
    machine:
      docker_layer_caching: true
    environment:
      - DOCKER_BUILDKIT: '1'
    steps:
      - checkout
      - run:
          command: |
            echo "hello world"
            echo "{ \"experimental\": true }"  | sudo tee /etc/docker/daemon.json
            sudo service docker restart
            docker version
            docker build -t myimage .
  splitting-test:
    docker:
      - image: circleci/node:11.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Jest test by splitting
          command: |
            npm install
            TESTFILES=$(circleci tests glob "./src/*.test.js" | circleci tests split --split-by=timings)
            echo ${TESTFILES}
            npm run test ${TESTFILES}
  test:
    docker:
      - image: circleci/node:11.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - config/share_key
      - store_test_results:
          path: test_results
      - run: npm run test