version: 2.1

# What I want to be able to do is
# call \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\" -host_arch=amd64 -arch=amd64
# Which works fine on azure pipelines and over ssh

orbs:
  win: circleci/windows@1.0.0

jobs:
  example-one:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: show envs
          command: gci env:* | sort-object name

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - example-one