version: 2.1
parameters:
  sophie:
    type: string
    default: ""
jobs:
  myjob:
    docker:
    - image: circleci/node:10.17.0
    steps:
    - checkout
    - run:
        name: Create build folder
        command: |
          npm i
          ls
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob:
          context: aws