version: 2.1

myexecutor: &executor
  docker:
    - image: circleci/node:latest

jobs:
  test:
    <<: *executor
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Glob all test in this repo
          command: |
            export TEST_FILES=$(circleci tests glob './' | circleci tests split)
            echo ${TEST_FILES}
            npm run echo

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - test