version: 2.1
parameters:
  SMOKE_TEST:
    type: boolean
    default: false
  DEPLOYMENT:
    type: boolean
    default: false
jobs:
  myjob:
    docker:
    - image: circleci/node:10.17.0
    steps:
    - checkout
    - when:
        condition: <<pipeline.parameters.SMOKE_TEST>>
        steps:
          - run: echo "start smoke test"
    - when:
        condition: <<pipeline.parameters.DEPLOYMENT>>
        steps:
          - run: echo "start deployment"
workflows:
  version: 2
  my-workflow:
    jobs:
      - myjob