version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:11.1.0
jobs:
  step1_foo:
    executor: node-executor
    steps:
      - checkout
      - run: echo 'step1_foo'
  step2_foo:
    executor: node-executor
    steps:
      - checkout
      - run: echo 'step2_foo'
  step3_foo:
    executor: node-executor
    steps:
      - checkout
      - run: echo 'step3_foo'
workflows:
  version: 2
  "See the orders":
    jobs:
      - step1_foo
      - step2_foo:
          requires:
            - step1_foo
      - step3_foo:
          requires:
            - step1_foo
            - step2_foo