version: 2.1
jobs:
  persistWorkspace:
    docker:
      - image: circleci/node:10
    working_directory: ~/config
    steps:
      - checkout
      - run:
          name: see the directory
          command: ls
      - persist_to_workspace:
          root: ~/config
          path: /*
  attachWorkspace:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ~/config

workflows:
  version: 2
  build-deploy:
    jobs:
      - persistWorkspace
      - attachWorkspace:
          requires:
            - persistWorkspace
          