version: 2.1

jobs:
  restore_cache_build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: source-v1--
      # if cache successfully restored, then there would be path
      - run:
          name: check cache path
          command: |
            CACHE_DIR="~/projectPath"
            if [ -d "$CACHE_DIR" ]; then
              echo "It means there is cache restored"
              exit 1 # finish build
            fi
      - run:
          name: check when
          command: echo "hello world"
          when: on_success
workflows:
  start_build:
    jobs:
      - restore_cache_build
