version: 2.1
jobs:
  cmake:
    docker:
    - image: circleci/ruby:2.6.4-node-browsers
    steps:
      - checkout
      - run:
          name: Add CMake to avoid error
          command: sudo apt-get install cmake

workflows:
  version: 2
  build-deploy:
    jobs:
      - cmake
